### ISSUE TITLE
ToC doesn't display: wrong css location?

### ISSUE THREAD

**Issue by jlgarnier** [iridescent-dev/pico-toc-plugin#6]
Hi all!
I've installed the plugin but may have used a wrong location, as I don't really get what you call the "project". Here's my structure:

- Plugin is installed in **nextcloud/data/appdata_oc7hmh3uqrlj/cms_pico/plugins/TableOfContents/**
- Custome theme is installed in **nextcloud/data/appdata_oc7hmh3uqrlj/cms_pico/themes/mytheme/** (simple copy of default theme)
- I've updated nextcloud/data/appdata_oc7hmh3uqrlj/cms_pico/themes/mytheme/index.twig with the required line
`<link rel="stylesheet" href="{{ base_url }}/plugins/TableOfContents/style.css">`

When I add <toc max-level="3" heading="Table of Contents" /> in my index.md file, it just doesn't display, so I suppose I've put some files in a wrong location.

Thanks in advance for any help!

**Comment by iridescent-dev** [comment]
Can I see the complete tree structure of your project?
Here is the structure of my project:
<img src="https://user-images.githubusercontent.com/25682686/137692284-c75ac41f-89b6-47ac-a8dc-613c936f0123.png" alt="image" width="200">

After re-reading your messages, I don't understand what you mean here:
> I may have misread the doc: should the plugin be put in `<myPicosite>/plugins/`, beside the `<myPicosite>/content and /assets` directories? In that case, that would not be a generic plugin for PicoCMS, and would not appear in the PicoCMS Custom Extensions settings...

Your project is separated in the `myPicosite` and `cms_pico` folders?
What do you mean by "generic plugin"?

In any case, if the `plugins_url` is incorrectly resolved by Pico, maybe you can try to indicate to it in the `config.yml` file:
```
plugins_url: ~                      # Pico will try to guess the URL to the plugins dir of your installation;
                                    #     If this fails, override it here. Example: https://example.com/pico/plugins/
```

**Comment by jlgarnier** [comment]
Hi, back from a short vacation...

To clarify my request, here's some additional information:
- The root directory for Nextcloud is `/home/nextcloud/html/`. I had to move Docker to home, which is hosted onto its own disk storage.
- Pico CMS application is installed (through NC appstore) in `/home/nextcloud/html/custom_apps/cms_pico/`.
- Default settings are stored in `/home/nextcloud/data/appdata_oc7hmh3uqrlj/cms_pico/`.
- ToC plugin is installed in `/home/nextcloud/data/appdata_oc7hmh3uqrlj/cms_pico/plugins/TableOfContents/`.
- Example site "Admin News" has been created in `/home/nextcloud/data/newuser/files/adminews/`.

This architecture should not have any impact on the use of the plugin, as it should find its way through the folders, but maybe some files should be moved to other locations: please tell me and I'll fix them. However, please remind that the only location I chosed is the ToC plugin folder...

Thanks for your support!

**Comment by iridescent-dev** [comment]
I don't know nextcloud at all, but I tried to do some research.

In this documentation https://github.com/nextcloud/cms_pico#installation, I see that the use of composer is possible, have you tried installing the plugin with composer in order to see where it is installed by Pico?

In this documentation https://apps.nextcloud.com/apps/cms_pico, I see that there is an interface to add plugins, did you use it?
<img src="https://raw.githubusercontent.com/nextcloud/cms_pico/master/screenshots/custom_plugins.png"/>

Finally, I see in this article https://www.robertson.net.nz/tips/nextcloud-picocms-app that "Plugins have to be uploaded into `your_nextcloud_root/apps/cms_pico/Pico/plugins/`".

The last 2 links do not seem to agree on the location of the plugins folder.

---

You told me that `{{ plugins_url }}/TableOfContents/style.css` was resolved into `/apps/cms_pico/pico/myPicosite/plugins/TableOfContents/style.css`, so I think Pico expects plugins to be in `/apps/cms_pico/pico/myPicosite/plugins`.

Anyway, I think the plugin files should stay together in the ToC folder, and I would advise you to try moving the plugins folder to other locations to see what works.

**Comment by jlgarnier** [comment]
As Nextcloud was offering an automated installation, this is what I used and didn't try to use composer. However, I've checked the config default settings and external applications are stored in html/custom_apps, while core applications are store in html/apps. Don't know if this could have any impact...

Therefore ToC plugin has been activated through Pico CMS interface, and was previously copied into `data/appdata_oc7hmh3uqrlj/cms_pico/plugins/`, as required by NC. I will try to move it into `nextcloud_root/custom_apps/cms_pico/Pico/plugins/` to see if it's correctly loaded.

Regarding the style.css issue, my picosite is actually created (by Pïco CMS) into `data/username/files/picositename`: should I move the ToC plugin into `data/username/files/picositename/plugin`? This would definitely force me to duplicate the plugin for each picosite!

Back with some results soon!

**Comment by jlgarnier** [comment]
Back...

**1st try**: moved the plugin to `nextcloud_root/custom_apps/cms_pico/plugins/TableOfContents`: NC doesn't raise any error, but the ToC still doesn't display.

**2nd try**: moved the plugin to `nextcloud_root/custom_apps/cms_pico/plugins/TableOfContents`: this folder already exists and includes a 'PicoDeprecated' folder, so I was expecting this was the good location. However, no error from NC, but the ToC still doesn't display.

I've noticed that a copy of the plugin (and my custom theme too) is created into `nextcloud_root/custom_apps/cms_pico/appdata_public/plugins/pvhUV9JXn7/TableOfContents`: is this the standard Pico CMS behavior?

Then, on the Pico CMS settings page, I tried to refresh the list of plugins and themes: unexpected error is thrown. Moved back the TableOfContents folder to `data/appdata_oc7hmh3uqrlj/cms_pico/plugins/`, reloaded the settings page, ToC and custom theme are proposed again and I can just click the [+] button to add them to the (normally) activated add-ons. Unfortunately, the ToC still doesn't display... 😢

Reminder: the index.md file only contains
```
# The Admin News

<toc min-level="2" max-level="2" heading="Table of Contents" />

## What's new with Nextcloud?

This (micro)website is your resources one-stop-shop: **tips and tricks**, update news, main tickets followup, you'll find plenty of information from your beloved Admin here!

## How to...?

Users who are new to Nextcloud may be impressed by its power, but do you know you can do much (work) with less (effort)?

| How to? | Read how |
| --- | --- |
| Create my own blog or *knowledge base* | Ask your admin if you don't find the Pico application in your private menu and create a Pico website |
| Open a ticket | Just mail your issue (with context) to your admin |
```

Could min-level=max-level=2 trigger this issue?

Can you please also confirm that the ToC folder only include style.css + TableOfContents.php files?

I'm a bit at lost now, as I really can't see where I could paste those files to have them processed by Pico CMS... 🤔

**Comment by iridescent-dev** [comment]
Bad news!

`min-level="2" max-level="2"` could not trigger this issue, I tested your index.md file and here is the toc I got:
![image](https://user-images.githubusercontent.com/25682686/140408612-04b9b89d-c36f-4b0b-b28d-0f0629c6a7eb.png)

For your other question: yes, ToC folder only include style.css + TableOfContents.php files.

I found this issue which maybe can help you: https://github.com/nextcloud/cms_pico/issues/104
I think themes and plugins work the same.

Otherwise I suggest you to open an issue on this [Github](https://github.com/nextcloud/cms_pico/issues), they can probably help you better than me.

Sorry I couldn't help you more

**Comment by jlgarnier** [comment]
Thanks a lot for your help! I'll then try to go further with the Pico CMS dev team, opening a ticket for his issue. I'll let you know of their feedback!

**Comment by jlgarnier** [comment]
Hi,

Here's the answer I received from Pico CMS team:

_Unfortunately plugins using custom HTML tags (like `<toc />`) aren't supported by Pico CMS for Nextcloud for security reasons. All contents are fed into HTMLPurifier to remove potentially malicious contents (like JavaScript). To do so, HTMLPurifier removes everything it doesn't understand - including the `<toc />` element.
You might wanna ask the plugin developer to update the plugin to either use another marker instead (e.g. [toc]), or, even better, allow theme developers to add TOCs to the theme instead (a TOC semantically is no part of a website's contents)._

I'm then wondering how you manage to get the ToC to display with my index.md file... 🤔 Which Nextcloud & Pico CMS versions are you using?

**Comment by iridescent-dev** [comment]
I have never used Nexcloud and therefore I have never tested the plugin with Nextcloud.

I just modified the plugin to use a `[toc]` marker as they recommended.  It's committed on the [develop branch](https://github.com/iridescent-dev/pico-toc-plugin/tree/develop). Can you test this version with Nextcloud and tell me if it works?

**Comment by jlgarnier** [comment]
Hi,

I've updated the plugin and my index.md files to now have `[toc min-level="2" max-level="2" heading="Table of Contents"]`. Unfortunately the tag is not processed and just displays as is (see picture below).

Plugin files are still in `/home/nextcloud/data/appdata_oc7hmh3uqrlj/cms_pico/plugins/TableOfContents/` as requested by Nextcloud... I also tried to update the files in `/home/nextcloud/html/custom_apps/cms_pico/appdata_public/plugins/YNuno1eztY/TableOfContents/` but got the same result.

I also tried to update the twig file of my template and got a new display: ![Capture d’écran 2021-11-15 102620](https://user-images.githubusercontent.com/26840059/141756463-a907db00-b90a-43ff-9452-56b88ff2607b.png).

```
<div id="main" role="main">
        <div class="container">
            {{ toc }}
            {{ content }}
        </div>
    </div>
```

This is unsettling and I'll then answer to Nextcloud to get more information about the processing of plugins (and plugins of plugins) and come back to this thread.

Thanks again for your support!

**Comment by iridescent-dev** [comment]
Sorry, I forgot to tell you that I had to change the way the options are given. Look at the [example](https://github.com/iridescent-dev/pico-toc-plugin/tree/develop#example) in the readme file.

You just have to add the `[toc]` marker in the content and options are added in the Meta headers. Options are also used to display the `{{ toc }}` Twig variable in your template.

This is what your `index.md` file should look like, don't forget to add your other meta headers to it.

```
---
Title: The Admin News
TOC:
  min_level: 2
  max_level: 2
  heading: Table of Contents
---

# The Admin News

[toc]

## What's new with Nextcloud?

This (micro)website is your resources one-stop-shop: **tips and tricks**, update news, main tickets followup, you'll find plenty of information from your beloved Admin here!

## How to...?

Users who are new to Nextcloud may be impressed by its power, but do you know you can do much (work) with less (effort)?

| How to? | Read how |
| --- | --- |
| Create my own blog or *knowledge base* | Ask your admin if you don't find the Pico application in your private menu and create a Pico website |
| Open a ticket | Just mail your issue (with context) to your admin |
```

At last! Glad to see the table of contents appear!

**Comment by jlgarnier** [comment]
That did the trick! The ToC now displays where the [toc] tag is put with the expected styles
![Capture d’écran 2021-11-15 113947](https://user-images.githubusercontent.com/26840059/141767683-9ca75ba1-dad3-45c6-9b47-92bae21a13c8.png)
!
Thank you very much for your support! Will you update the production branch now?

**Comment by iridescent-dev** [comment]
It's done!

**Comment by jlgarnier** [comment]
Thanks a lot, have a great day!
